### ISSUE TITLE
Back to index in the Allen's grammar very slow (sometimes)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/grammar-allen-greenough#11]
I did experience the Back to Index slowness today again (May 6, 2020). Actually at one point it just did not do anything, while the language selector worked well. I had to close and reopen the grammar. As I had to check links to different sections of the conjugation chapter, I did use back to index heavily before it just stopped working.

**Comment by balmas** [comment]
ok, I commented out all the video iframes. Curious to know if it makes any difference.

**Comment by monzug** [comment]
I used it quite a bit today and I had no issues. good point, Irina.
