### ISSUE TITLE
add index

### ISSUE THREAD

**Issue by balmas** [alpheios-project/grammar-allen-greenough#8]
add the back-of-the-book index and link it from the TOC

**Comment by balmas** [comment]
@monzug your latest changes and the updated fullindex file with the references replaced is live now. Let me know how it looks to you.

**Comment by monzug** [comment]
Index is there. Should Glossary and Index be in bold like a chapter title?

![glos-index](https://user-images.githubusercontent.com/41396793/81812789-9d499e00-94f4-11ea-85f2-c3ce9148c8b2.JPG)

**Comment by balmas** [comment]
Ah, probably. That's an easy fix. Will also fix the TOC link for Verb Endings.

**Comment by monzug** [comment]
cool. I wasn't sure which style to apply for Glossary and Index. Thanks

**Comment by balmas** [comment]
done

**Comment by monzug** [comment]
excellent
